//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOAD_Nhom8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OOADEntities : DbContext
    {
        public OOADEntities()
            : base("name=OOADEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<NganHang> NganHangs { get; set; }
        public virtual DbSet<PhieuThueXe> PhieuThueXes { get; set; }
        public virtual DbSet<TheNganHang> TheNganHangs { get; set; }
        public virtual DbSet<TheThueXe> TheThueXes { get; set; }
        public virtual DbSet<XeDap> XeDaps { get; set; }
    }
}
