//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOAD_Nhom8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThueXe
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> ThoiGianMuon { get; set; }
        public Nullable<System.DateTime> ThoiGianTra { get; set; }
        public Nullable<int> MaTheThueXe { get; set; }
        public Nullable<int> MaXe { get; set; }
    
        public virtual TheThueXe TheThueXe { get; set; }
        public virtual XeDap XeDap { get; set; }
    }
}
