//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOAD_Nhom8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheNganHang
    {
        public int Id { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaNganHang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NganHang NganHang { get; set; }
    }
}
