//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOAD_Nhom8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheThueXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheThueXe()
        {
            this.PhieuThueXes = new HashSet<PhieuThueXe>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> NgayLamThe { get; set; }
        public Nullable<int> LoaiThe { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaQuanLy { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThueXe> PhieuThueXes { get; set; }
    }
}
